package agency;

public interface IndividualFactory<T extends Individual> extends XMLConfigurable {
  /**
   * Creates a new individual, not based on any parent individuals. Typically,
   * the values will be based on how the IndividualFactory was configured at
   * program start.
   * 
   * When a population is first initialized, its individuals will have been
   * generated by this function.
   * 
   * @return A new individual.
   */
  T create();

  /**
   * In some agent models, the range of allowable values in an agents' genome
   * will be restricted. These limits may have been exeeded by some other
   * process, e.g., mutation. This function alters the specified individual to
   * keep genome values within these limits.
   * 
   * @param ind
   */
  void limit(final T ind);
}
